### ISSUE TITLE
use more async/await

### ISSUE THREAD

**Issue by Karyum** [WebAhead6/DOGGO#3]
i'll provide examples for how to change it to async/await

[these lines of code](https://github.com/WebAhead6/DOGGO/blob/master/src/controllers/doggoDaily.js#L13-L17)
or
```javascript
exports.results = (req, res) => {
  model.fetchDoggoDaily().then((result) => {
    return res.redirect("/user/" + res.locals.id);
  });
};
```
to
```javascript
exports.results = await (req, res) => {
  try {
    const doggos = await model.fetchDoggoDaily()
    return res.redirect("/user/" + res.locals.id);
  } catch(err){
     return res.redirect("/login");
  }
};
```

here are some more blocks of code that could really use async/await

https://github.com/WebAhead6/DOGGO/blob/master/src/controllers/doggoDaily.js#L19-L41
https://github.com/WebAhead6/DOGGO/blob/master/src/controllers/doggoDaily.js#L43-L49

PS. the `auth.js` looks awesome

**Comment by Tarekb93** [comment]
DONE.
