### ISSUE TITLE
add the navbar to the header partial

### ISSUE THREAD

**Issue by Karyum** [WebAhead6/DOGGO#7]
we should take these lines of code from different views
https://github.com/WebAhead6/DOGGO/blob/master/src/views/registerR.hbs#L1-L2
https://github.com/WebAhead6/DOGGO/blob/master/src/views/home.hbs#L5-L6
https://github.com/WebAhead6/DOGGO/blob/master/src/views/doggoDaily.hbs#L3-L4

and put them in the header partial, just in case you would want to use them in the future, to hide or show links in that partial you use  the `res.render('', {})` for example

```javascript

res.render('register', {
  showHomeLink: true,
  showRegisterLink: true
})
```

**Comment by Tarekb93** [comment]
done
